### ISSUE TITLE
For Version 2

### ISSUE THREAD

**Issue by Open343** [visualcookie/slim-sentinel-auth#3]
Hi guys
You are a nice man, you did it, although for a long time. Some advice for you version 2.x

For administration dashboard.
You can choose startbootstrap-SB-Admin-2, it is a good choice. See https://github.com/BlackrockDigital/startbootstrap-sb-admin-2

Views for sign in and sign up
See https://github.com/userfrosting/UserFrosting 
For sentinel and for slim. It's very large, very complex. And i think your code should not write so much.

Other one
I recommend that you support multiple templates in the initial. like resources/views/template-name(default)/*.twig or other style.

I think you can support i18n/l10n in the future.

By the way. I would like to ask you whether the Sentinel supports pgsql and SQLite? If possible, how to do it? Thank you!

I'm so sorry my little English. Thanks Bing translator. Misnomer also please forgive me. Wish to work smoothly for you.

**Comment by visualcookie** [comment]
Hi @Open343,

sorry for the late reply. Finally had the time to get back working on version 2.

To your recommendations: I'm working on keeping the system as simple as possible and as customizable as possible, since it will be most likely a "bootstrapping" authentication system, which you might want to extend yourself (like the Laravel 5 default authentication). I've had an eye on UserFrosting before, but it's way to big for such a small purpose.

The new version will come with a admin panel based on Bootstrap 4 (currently in Alpha). Multiple templates is definitely what I'm considering at the moment as well as i18n/l10n support. It's not in the list yet, because I want to get the system ready first and then put in the features.

Thanks for your ideas so far. Took them on the list. :)
